---
title: "Course Preliminaries"
date: ""
format:
  revealjs:
    theme: simple
    slide-number: true
    transition: fade
    incremental: true
    chalkboard: false
    width: 1280
    height: 720
    margin: 0.08
    embed-resources: true
  # beamer:
  #   theme: metropolis
  #   aspectratio: 169
  #   incremental: true
  #   embed-resources: true
  # pptx:
  #   slide-level: 2
execute:
  echo: true
  warning: false
  message: false
---

## Course Background
- FRSC 2020H is an undergraduate course in the FRSC program, that:
  - covers strategies, practices, tools and resources that support effective investigation
- lecture modules cover *general* strategies and theory
- lab modules cover *specific* techniques and software tools

::: {.notes}
- this is one of the most important classes in our program, it really emphasizes the skills and ideas you need to succeed in university and as an independent researcher (which we all are)
- my personal hope is that you use this class to really figure out who you are as a learner/thinker, and hopefully develop a feeling for what you want to do in your upper years as a university student
  - for example, maybe looking into doing an undergraduate thesis, or community based research, maybe look into finding volunteer work or certification that can help you on the job market? etc.

:::

## Course Facilitators
::: {.nonincremental}
- **Instructor:** Arun Moorthy; arunmoorthy@trentu.ca; DNA B108.11; Tuesday 9-11 am
- **Staff Lab Demonstrator:** Adrian Borlestean; aborlestean@trentu.ca; DNA B108.04
- **Graduate Teaching Assistant:** Irina Badell; 
- **Student Lab Demonstrators:** Lauren Campbell; 
- **Student Lab Demonstrators:** Jonathan Shafer;
- **Student Lab Demonstrators:** Katie Wall;
:::

::: {.notes}
- There is more about all of your facilitators in the course welcome module--so please feel free to read up on us.
- spend a moment highlighting who you are since the students may not be familiar:
 - love learning (thus research). My primary research (i.e., what I get paid to study) are drugs, specifically developing mathematical tools to better understand the relationships between the chemical measurements of drugs. 
 - But I also investigate other types of chemicals (emerging environmental contaminants)
 - also interested in other types of physical evidence (e.g., handwriting, documents)
 - generally speaking, I enjoy math problems and trying to understand how we better utilize mathematical approaches in forensic science
 - I also love music, I love basketball, I love history, learning about people
- segue into the idea of students doing the introduction quiz. There a 100% chance I won't get to know each of you by name and face, but I'd like to try. Please fill out the introduction quiz with 10 days of having access to the course blackboard. For most of you, that will be September 20th.. 

:::



## Peer Note-taking Support

::: {.nonincremental}
- **Request:** Share your notes with Student Accessibility Services, who will redirect them to your classmates that need accessibility support. 
- **Benefit to you:** You'll receive a certificate at the end of the course, and the service will appear on your co-curricular record. 
- **How to volunteer:** sign up online through the SAS Portal on MyTrent $\rightarrow$ Academic Support $\rightarrow$ Support $\rightarrow$ SAS Portal $\rightarrow$ Volunteer Note-taker sign-up: log in & upload.
:::

::: {.notes}


:::

## Course Structure
- Lecture Modules will be available on Thursday mornings as outlined in syllabus
  - Modules will contain a video presentation (~30-60 minutes) and a link to the HTML "slides", also a link to a content quiz
- Lab Modules will also be available on Thursday mornings as outlined in syllabus
  - Modules will contain a video presentation (~10-20 minutes) and a link to the HTML "slides", also a link to a lab test
  
::: {.notes}


:::

## Lab Meetings
- there are in-person and remote lab sections; please make sure you bring a laptop if you are in-person
  - starts with a review of the presentation (~10-20 minutes)
  - non-graded facilitated activity (~30-50 minutes)
  - open work time to work on your lab tests, content quizzes or major research assignments
  

## Deliverables


- Most of the course deliverables have been designed/chosen with the following goals:
  1. Learn/improve transferable and hirable skills in critical reading, writing and data analysis
  1. Learn/improve use of software tools that can help with research and investigative work in future courses (and careers)
  1. Build a portfolio of meaningful documents you can share with others.




::: {.notes}


:::


## Introduction Quiz

- Five short answer questions
  - answer questions only if you feel comfortable; will still get full grades if you submit "N/A" for any of the questions

- Goal of this quiz is for me to get to know you 

- Worth 2% of your final grade.

::: {.notes}


:::

## Content Quizzes (x 10)
- Each lecture module has 1 or 2 quizzes associated with it (longer lecture modules will have two quizzes)
- Quizzes contain 4 multiple choice or true/false questions that are selected randomly from designed pools of similarly challenging questions
- Questions released one at a time with no backtracking
- Ten minute time limit per quiz (with extended time for students with registered accommodations)
- Can try each quiz up to 3-times; we'll take the average of all attempts as your grade
- Worth 10% of your final grade

::: {.notes}


:::

## Lab Tests (x 4)
- Each lab module has an associated 10-15 question test
- Questions will be multiple choice, true/false or calculated numeric, and randomly selected from designed pools of similarly challenging questions
- All questions will be released at once so you don't need to complete questions in order
- We expect each test to take approximately 30 minutes; no time limit per test
- Can only attempt test one time
- Worth 20% of your final grade

::: {.notes}

:::

## Final Exam
- Scheduled Blackboard Exam during exam period (we'll find out actual date from registrars office in November)
- Two hours (with time extensions for students with registered accommodation)
- Exam will combine questions from content quizzes and lab tests, with some aspects of your major assignments
- Questions will be released one at a time with no backtracking
- Worth 32% of your final grade


 
::: {.notes}
- Will post a "mock exam" during the exam period that you can try twice
- Goal with practice exam to make sure students are comfortable with the format of the exam
- Also opportunity for us to verify that we have coded accommodations correctly
:::

## Annotated Bibliography (1/2)
- an annotated bibliography is an extended reading log that includes key information about the material being read (beyond just the citation information)
   - technical information e.g., article objective, methods, results
   - contextual information e.g., other information about the article authors
   - reflections e.g., your opinion on the article
- a good annotated bibliography is one that is useful to you when you conduct research

::: {.notes}

:::

## Annotated Bibliography (2/2)
- in this assignment, you'll construct an annotated bibliography based on a provided entry template (with guided questions)
- there are 8 readings you must include in your annotated bibliography; you can add entries for other articles you are reading (in this class or other classes) if you'd like
- Individual assignment
- Due on October 23 at 11:59 PM (Friday)
- Plan for it to take you about 18 hours
- Worth 10% of your final grade

::: {.notes}

:::


## Research Proposal (1/2)
- a research proposal is a formal document used to advocate for a potential research project, used to help a research acquired additional support
- the structure of a research proposal is tied to the funder (support provider)
- all good research proposals will have enough methodological detail that your reader believes what you propose can be done, and enough contextual motivation that your reader believes what you propose will be meaningful

## Research Proposal (2/2)
- In this assignment, you'll construct a research proposal by filling out the "FRSC 2020H Research Proposal Form" (on Blackboard)
- You can propose any research project--find something that means something to you
- You can work in groups of at most 3 students
- Due on November 13 at 11:59 PM (Friday)
- Plan for it to take you about 20 hours
- Worth 8% of your final grade

::: {.notes}

:::

## Data Presentation
- Critical analysis of scientific evidence (data) is an important skill; communicating your analysis is an equally important skill
- In this assignment, you'll create a short video presentation (5-minute max) describing your analysis of data--of your choice!
- You can work in groups of at most 3 students
- Due on November 27 at 11:59 PM (Friday)
- Plan for it to take you about 15 hours
- Worth 8% of your final grade

::: {.notes}

:::


## Article Critique
- This year, we are recommending that you read 3 perspective articles and one non-fiction book (all available for free)
- In this assignment, you'll write a short critique (i.e., critical review article, commentary) based on one of the readings; max 550 words
- Individual assignment
- Due on December 3rd at 11:59 PM (Thursday)
- Plan for it to take you about 10-30 hours
- Worth 10% of your final grade

::: {.notes}

:::




## Grades
- Note that all "assignments" have rubrics associated with them 
    - look at rubrics carefully!
    - **Grading Scale**: Excellent, Good, Good enough, Close, Needs Improvement, Incomplete
- Note that all "tests" will be graded for accuracy

::: {.fragment .center}
Remember that grades are not everything; focus on building your *Portfolio* with assignments you are proud to share.
:::

::: {.notes}

:::



## Course Policy (1/3)
- **Attendance**: You are encourage to attend your scheduled in-person or virtual lab session
  - you DO NOT need to contact me if you cannot attend; just make sure you complete your lab test using the resources posted online

- **Due Dates**: All tests and assignments are due as outlined in the syllabus.
  - Content quizzes submitted after the due date will not be graded
  - Lab Tests and Assignments submitted after the due date will be penalized at a rate of 5% per 30 minutes that the test/assignment is late.

::: {.notes}

:::

## Course Policy (2/3)
- **Uncontrollable Circumstances Exception**: If you are unable to submit one of your lab tests or major assignments due to something out of your control (e.g., sudden illness, accident), you can move up to 80% of the weight of your test/assignment to a future test/assignment in the same category
  - you must submit your request as an email to Arun (arunmoorthy@trentu.ca); no need to explain your circumstance
  - amount of weight that you move to a future assignment will drop 5% per half hour after the due date


## Course Policy (3/3)
- **Use of generative AI and other software tools**: In general, you may use generative AI tools (e.g., Microsoft Co-pilot) and other software tools to help you brainstorm ideas and learn concepts for assignments in this class. However, we have some specific requirements that you should adhere to: 

    1. All submitted work must be your own. I.e., Do not plagiarize.
    1. Any mistakes in your work due to use of generative AI or other software tools are YOUR responsibility and will be penalized accordingly. 
    1. DO NOT upload other peoples' work to a generative AI services; this is a breach of copyright. 


## {.center}

::: {.text-center}
A quick tour of blackboard
:::



## How to get the most out of this course
- schedule time to work on your:
  - content modules (on avg. 1 hour a week)
  - lab modules (on avg. 2 hours every other week) 
  - assignments (on avg. 4-7 hours a week)
- start your assignments early!
- take advantage of the "remote" aspect of the modules
- **find a group**
  - group work isn't always easy, but the work of a well-functioning group is always better than work of any of its individual member


## On Epistemology
- a branch of philosophy interested in the origin, nature and limits of human knowledge
- Some ways we think we know:
  - Personal experience 
  - Authority
  - Tradition
  - Intuition
  - Reasoning
  - Observation/evidence


::: {.notes}
- how do we know things? why do we believe things?
-  But all these individual methods of knowing are fallible 
:::

## What is science?
- a knowledge base constructed using the "scientific method"
- the scientific method is (an *iterative*) process for learning about anything, and can be summarized by the following general steps:
  - observing
  - recognizing/defining
  - hypothesizing
  - testing
  - (disseminating)

  
::: {.notes}
- many bodies of knowledge are described as "science" or "a science" and they are similar in that the knowledge was acquired by following the so-called "scientific method"
  - observing: to notice or perceive something (of interest) in a situation
  - recognizing/defining: using observations to recognize open questions or define problems
  - hypothesizing: using observations and other available information to infer solutions to the questions/problems
  - testing: designing models and/or experiments to evaluate hypotheses and predictions
    - (disseminating): sharing results so others can make observations, and build knowledge
- the key to what's the scientific method so effective is that we allow iteration, we allow for ideas to grow and change as new information becomes available--science is dynamic knowledge
- the verb to iterate means to cycle/repeat through a process, but leverage information learned through previous iterations (passes through the method)

:::

## History of scientific development (1/5)
- Approximately 1600 BCE - Edwin Smith Papyrus
  - Describes 48 battlefield injuries and the surgical treatments employed, considered to be the world's earliest known medical document and contains essential elements of the scientific method
  - Purchased in 1862 by egyptologist Edwin Smith

::: {.notes}
- the scientific method didn't just get written down as a fully formed idea, it itself developed over time--through iteration
:::

## History of scientific development (2/5)
- 4th Century BCE - Greek Philosophy
  - **Deductive Reasoning**: A form of reasoning in which a conclusion is drawn from accepted premises
  - Top-Down reasoning
  - Susceptible to failure if any of the premises are incorrect

::: {.notes}

:::

## History of scientific development (3/5)
- 4th Century BCE- Greek Philosophy
  - **Inductive Reasoning**: A form of reasoning in which an inference (hypothesis) is generated based on observations
  - Bottom-up reasoning
  - Always inconclusive, but can be used to generate theory, hypotheses, and probabilistic statements

::: {.notes}

:::

## History of scientific development (4/5)
- 8th-15th century CE - Islamic Science; 12th-16th century CE European Science
  - Extend deductive-inductive reasoning with controlled experimentation (empiricism)
  - Increased emphasis on mathematics to formulate and describe theory
  - Introduced principle of parsimony: An explanation or theory should be as simple as possible and contain just enough terms to explain the facts. (Ockham's Razor)
  
::: {.notes}

:::

## History of scientific development (5/5)
- 16th - 18th century CE - Scientific Revolution
  - 1543 - Copernicus published "On the revolutions of the heavenly spheres"" proposed that the earth is not center-point of the universe
  - 1655 - Hook published "Micrographia"; described observations under a microscope
  - By the end of the 18th century, the scientific method (iterative inductive-deducting reasoning with well-designed experiments) was widely regarded as the best strategy for acquiring knowledge (learning)

::: {.notes}

:::



## Modern thoughts on the scientific method
- In 1934, Karl Popper introduced the concept of "falsifiabilty" to determine whether a statement (e.g., a hypothesis or theory) was scientific:
  - a statement is considered scientific if it can be falsified (refuted) using an empirical test
- At present, *most* people agree that the scientific method is the reliable approach to learning, but many people are challenging the way it is taught 
  - [Windschitl et al. Beyond the scientific method: Model-based inquiry as a paradigm of preference for school science investigations. Science Education, 92(5), 941-967. ](https://doi.org/10.1002/sce.20259){data-preview-link="true"}
  
## Basic application of the scientific method (1/2)

- **Situation**: You are working as a forensic chemist in a drug lab. You are asked to evaluate a baggie that contains an unidentified white powder. 

- **Observation**: The baggie is a standard size for illegal recreational drugs, and the visual consistency of the powder is similar to cocaine.

## Basic application of the scientific method (2/2)

- **Hypothesis**: The substance in the baggie is cocaine.

- **Test**: We can use lab techniques (analytical chemistry) to determine whether sample is cocaine. We take a **sample** of the material to the lab.

- **Results**: The lab results suggest that the sample is not cocaine.

- **Follow up questions**: ...

::: {.notes}
- is it another illegal recreational drug?
- did you take enough sample?
- what was the lab technique used?
- was the analytical instrument working correctly?
- there is a danger of trying too hard to make your test meet your expectations--one of the biggest abuses of scientific method is tweaking.
:::

## The scientific method in forensic science
- Forensic science has unique challenges:
    - Usually we're investigating something bad: crime, accident, catastrophic event; hard not form a bias
    - We only have access to limited information; there's a lot of uncertainty
    - Being wrong can have significant consequences; we want to minimize errors
    - We're communicating findings to a non-technical audience; there are opportunities for misunderstanding
- Important that we use systematic (and validated) approaches to minimize these challenges

## Good Science is...
1. **Empirical.**
1. **Rational.**
1. **Testable.**
1. **Parsimonious.**
1. **Explainable.**
1. **Reliable.**
1. **Tentative.**

:::{.notes}
Empirical: based on observations or experience

Rational: consistent with reason or logic

Testable: able to be tested

Parsimonious: does not make many assumptions

Explainable: able to be explained

Reliable: able to be trusted



Tentative: not certain of fixed; provisional
:::

## Some terms to know (1/4)
- Information: a description or statement or other form of expression

- Fact: information that has been verified as true

- Knowledge: the collection of facts and information known by an individual

## Some terms to know (2/4)
- Observing: to notice or perceive something (of interest) in a situation

- Hypothesis: a potential answer to a question/problem; not assumed to be true

- Falsifiability: the ability of a statement to be proven false; a required property of a scientific hypothesis

- Inference: a statement based on the evaluation of available data or evidence; usually stated with some uncertainty



## Some terms to know (3/4)
- Experiment: a procedure for collecting observations, testing a hypothesis, or demonstrating a fact

- Deductive reasoning: a form of reasoning in which a conclusion is drawn logically from accepted premises

- Inductive reasoning: a form of reasoning in which an inference (hypothesis) is generated based on observation

## Some terms to know (4/4)
- Iterative process: a cyclical process where each cycle is informed by the previous cycles (also known as iterations)

- Hypothetico-deductive reasoning: an alternative description of the iterative inductive-deductive reasoning cycle that is core to the scientific method

## {.center}

::: {.text-center}
Good luck with content quiz 1!<br>(Due September 17 at 11:59 PM)
:::
