---
title: "Reading and Note-taking"
date: ""
format:
  revealjs:
    theme: simple
    slide-number: true
    transition: fade
    incremental: true
    chalkboard: false
    width: 1280
    height: 720
    margin: 0.08
    css: ../styles.css
    embed-resources: true
  # beamer:
  #   theme: metropolis
  #   aspectratio: 169
  #   incremental: true
  #   embed-resources: true
  # pptx:
  #   slide-level: 2
execute:
  echo: true
  warning: false
  message: false
---

## Why read science?

- Traditionally, scientific knowledge is shared through written documents. 

- We read science to 
  - identify and verify knowledge that can be used in professional work and decision-making
  - identify and verify *techniques and methods* that we can use; develop *new questions* based on the findings of the authors
  - be entertained and feed our curiousity 


::: {.notes}
 - mention that this lab presentation re-iterates some of the content that will be included in lecture module 2; mention that we'll be talking about different types of scientific documents in lecture module 3; mention that we'll be working through creating some written documents throughout this course
 - highlight that the subpoints are linking to "Information Gathering", "Finding Inspiration" and "Being entertainment/a sense of wonder" from lecture module 2
:::

## Why is reading science hard?

- Everything is new to the reader
- Everything is new to the author
- Everything moves quickly / People don't have a lot of time 

::: {.fragment .center}
**Taking your time and learning how to read science is a super power!**
:::

::: {.notes}

- explain that usually, as a reader, you are reading papers or technical notes or even books in a research area that you are new to. so you may not be familiar with some of the concepts, foundational theories, or even writing practices of the field (some areas have "predictable" syntax, notation, etc.)

- explain a subtle but important fact--many scientific publications are the first time the author is explaning something (especially true for journal articles). Authors might understand their results perfectly, but still are figuring out best ways to share the ideas. 

- explain these two challenges are linked to a societal challenge: science and life **appear** to move quickly. Authors do not take as much time to think about what they want to share, they may not edit as carefully as they like. Readers *don't have the time* to learn foundations of a research area, don't try very hard to **engage** if they don't understand the article the first-time they read it


- emphasize that building quality reading skills takes time and practice.. it's more than just reading the words, its trying to appreciate and understand what the author is trying to say. Also emphasize that being "slow" now as a student is a good thing--better to be slow now and learn the skills well
:::



## Building a reading strategy
- getting better at reading takes time and requires practice
- it also helps to have a strategy
- Choose the elements of your strategy:
  - content: what do you want to get better at reading?
  - frequency: how often are you going to read?
  - tracking: how are you going to track your reading/progress?
  - community: who will you talk about your readings with?

::: {.notes}


:::

## Tracking your reading
- a reading log is a document/tool that scientists use to keep track of their reading
  - can be a physical document you edit by hand
  - can be a digital document you edit on a computer/phone
  - can be embedded within a software tool

::: {.notes}
- note that logs are tools not just for scientists--other researchers, writers, marketters, etc.
  - explain that the "log" can take any form (a note on your phone to a dedicated spreadsheet)
:::

## Tracking your reading
- an annotated bibliography extends the idea of a reading log to include key information about the materials being read
  - having a well-formatted annotated bibliography can be incredibly useful as a scientist

::: {.notes}
- this key information could include author information, summary of the material, an appraisal/critical evaluation, etc.
- especially useful when trying to design experiments, remember facts and figures, write papers, etc.
- make a note that it is common for scientst to build an annotated bibliography as the first step when they are starting a new research project

:::


## Building an annotated bibliography
- there are seemingly infinite ways to construct an annotated bibliography; the most important quality of an annotated bibliography is that it is useful to the user(s)
- in this class, we'll use a template annotated bibliography developed by Arun

::: {.notes}
- explain that if you can't pull the information you need to help you with the project you are working on, then your annotated bibliography is not well constructed
- note that the template includes questions to help guide reading/thinking about the material
:::


## Learning a reference manager
- a reference manager is a software tool to help you organize your readings
- many modern reference managers allow you to:
  - upload and annotate your pdfs
  - sync your library across multiple computers
  - include searchable tags
  - interface with word processors to automate citations and bibliography creation
- it will be incredibly advantageous to become comfortable with a reference manager

::: {.notes}
- make a note of several of the popular open-source and commercially available references managers: mendeley, endnote, refworks,... new references managers everyday
:::

## Zotero
- a popular open-source reference manager that is supported at Trent University:
  - https://www.zotero.org/
- you can create a free account so you can sync Zotero across multiple device
- you can download and use Zotero without an accout (on a single machine)
- you can install the MS-Word plug-in to integrate Zotero with the desktop version of Word

::: {.notes}
- note that it is Arun's favourite reference manager, and staff in the Library and through Academic Skills should be able to assist students with Zotero issues
- also note that they have paid tiers of zotero accounts with increased storage and other features--might be handy if you end up reading a lot of papers
- provide a live demo of (5-10 minutes) Zotero. The key things to showcase:
  - adding a file to a zotero library
  - opening the paper so you can annotate it
  - creating searchable tags
  - adding a reference by just citation
  - adding a manual entry link to a youtube video (as an example)
  - generating a bibliography in a specified format
  - linking to word, adding citations, adding a bibliography
    - reordering sentences, updating bibliography, changing bibliography format
:::

# Activity

::: {.notes}
Activity description is in MS Teams Folder
:::

# Open work time

## Things you might work on

::: {.nonincremental}
1. Lab Test 1
1. MA1: Annotated Bibliography
1. MA4: Article Critique
1. Start thinking about groups for MA2 and MA3 (if applicable)
:::

::: {.notes}
- Remind students that MA1 and MA4 are independent assignments, but that talking about what you're thinking about with peers is a good thing
- Remind students that they can also work on their lecture content quizzes if they have one to do

:::
